### ISSUE TITLE
Cannot use, login does not work right

### ISSUE THREAD

**Issue by RubenKelevra** [mohan43u/gistnotes#12]
I've installed the extension via Firefox, I've clicked on the new icon and logged in, via 2 factor. Then I've authorized the application... and the window switched over to the project-page here... but does not disappear. After this I've closed the window, but the second window also disappeared.

When I reopen the application again, the login-query window reappear again, where I've not logged in.

**Comment by mohan43u** [comment]
This was fixed. https://github.com/mohan43u/gistnotes/issues/11

Please use the 3.18 download link provided in the README.md file. To install the extension manually, use the following steps.
1. extract the zip into ~/.local/share/gnome-shell/extensions/gistnotes@mohan43u.gmail.com 
2. execute this commandline 

`
(ENABLED_EXTENSIONS=$(gsettings get org.gnome.shell enabled-extensions | sed "s/]$/,'gistnotes@mohan43u.gmail.com']/g"); gsettings set org.gnome.shell enabled-extensions "${ENABLED_EXTENSIONS}")
` 

someone in the gnome need to approve the latest version of this extension to fix the problem you are facing..
