### ISSUE TITLE
Failure: Typelib file for namespace 'WebKit' (any version) not found

### ISSUE THREAD

**Issue by jwhonce** [mohan43u/gistnotes#14]
Using a fresh install of Fedora26 workstation, I get the following failure:

$ gistbin

(gjs:14066): Gjs-WARNING **: JS ERROR: Error: Requiring WebKit, version none: Typelib file for namespace 'WebKit' (any version) not found
@/home/jhonce/.local/share/gnome-shell/extensions/gistnotes@mohan43u.gmail.com/github.js:19:7
@/home/jhonce/.local/share/gnome-shell/extensions/gistnotes@mohan43u.gmail.com/gistbin:7:7

JS_EvaluateScript() failed

RPM Details:
webkitgtk4-2.16.6-1.fc26.x86_64
webkitgtk4-plugin-process-gtk2-2.16.6-1.fc26.x86_64
webkitgtk4-jsc-2.16.6-1.fc26.x86_64
gjs-1.48.6-1.fc26.x86_64
gnome-shell-3.24.3-1.fc26.x86_64

Any suggestions or ideas on how to resolve this issue?  This did not happen on a machine that I had upgraded from Fedora25 to Fedora26.

**Comment by mohan43u** [comment]
Kindly install webkitgtk3. I have to port gistnotes from webkit to webkit2 to work with webkitgtk4 which is the default in fedora26.

**Comment by jwhonce** [comment]
Thanks, that did the trick.  A great time saving tool.
