### ISSUE TITLE
Waaaaay too much access is required!  ;-)

### ISSUE THREAD

**Issue by mdrmike** [mohan43u/gistnotes#4]
Ok, the extension is still a great idea,,, and I'm not likely to file any more issues... but this app requires waaay to much access to my personal kingdom for me to consider using it.   

I can understand granting **read/write access to gists**, and maybe this is a failing in the github API, but requiring **read and write access to all user data**, as well as **read and write to all public and private repo data** is just insane!

![screenshot from 2015-01-05 17 14 04](https://cloud.githubusercontent.com/assets/259940/5622851/fee55722-94fe-11e4-9170-37acee7b84bb.png)

**Comment by mohan43u** [comment]
I agree, I shouldn't include repo access for a tool which focus on gist. removed repo from scope. I tried to find a way to use read-only user data, but github api doesn't provide a way to use read-only user data.
https://developer.github.com/v3/oauth/#scopes
fixed https://github.com/mohan43u/gistnotes/commit/133ac16c2fd8854a620952106cbcea6b41ec47fe
