### ISSUE TITLE
Please add releases for manual installations

### ISSUE THREAD

**Issue by miwebguy** [mohan43u/gistnotes#9]
Gnome Extension site seems to trip up over proxy or something.
How about a release version that can be downloaded and installed with the extension manager.

**Comment by mohan43u** [comment]
Is it works beyond proxy? I didn't test it. I hope it will work if system wide proxy is available (libsoup's default proxy resolver comes into picture). Coming to your point, I'm not sure what kind of version you need. If you want to manually install it, you can follow these steps
1. download the gistnotes-master.zip from github ("download zip" button availabe near bottom right corner on every github repository page)
2. unzip and move(rename) gistnotes-master directory to 

```
~/.local/share/gnome-shell/extensions/'gistnotes@mohan43u.gmail.com'
```
1. enable the extension. thats all.

```
   $ gsettings set org.gnome.shell enabled-extensions ['gistnotes@mohan43u.gmail.com']
```

I'm really not getting you when you say "release version that can be downloaded', I believe you are expecting something like 'gistnotes-0.0.1.tar.gz' which you can use it with 'extension manager' (again, gnome don't have any official 'extension manager' app AFAIK)

**Comment by miwebguy** [comment]
Gnome/Tweak Tool/Install ShellExtension (uses zip, oddly)

Example: Check out MicheleG Dash - to Dock https://micheleg.github.io/dash-to-dock/download.html Manual installation section

**Comment by mohan43u** [comment]
added download links in the README file
